/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LocaleIndexRouteImport } from './routes/$locale.index'
import { Route as LocaleAboutRouteImport } from './routes/$locale.about'
import { Route as LocaleActionsRouteImport } from './routes/$locale.actions'
import { Route as LocaleContactRouteImport } from './routes/$locale.contact'
import { Route as LocaleGalleryRouteImport } from './routes/$locale.gallery'
import { Route as LocalePartnersRouteImport } from './routes/$locale.partners'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminActualitesRouteImport } from './routes/admin/actualites'
import { Route as AdminChiffresRouteImport } from './routes/admin/chiffres'
import { Route as AdminGalerieRouteImport } from './routes/admin/galerie'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminMessagesRouteImport } from './routes/admin/messages'
import { Route as AdminPartenairesRouteImport } from './routes/admin/partenaires'
import { Route as AdminProjetsRouteImport } from './routes/admin/projets'
import { Route as LocaleNewsIndexRouteImport } from './routes/$locale.news.index'
import { Route as LocaleNewsSlugRouteImport } from './routes/$locale.news.$slug'
import { Route as LocaleProjectsIndexRouteImport } from './routes/$locale.projects.index'
import { Route as LocaleProjectsSlugRouteImport } from './routes/$locale.projects.$slug'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAboutRoute = LocaleAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleActionsRoute = LocaleActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleContactRoute = LocaleContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleGalleryRoute = LocaleGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => LocaleRoute,
} as any)
const LocalePartnersRoute = LocalePartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => LocaleRoute,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActualitesRoute = AdminActualitesRouteImport.update({
  id: '/actualites',
  path: '/actualites',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChiffresRoute = AdminChiffresRouteImport.update({
  id: '/chiffres',
  path: '/chiffres',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalerieRoute = AdminGalerieRouteImport.update({
  id: '/galerie',
  path: '/galerie',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPartenairesRoute = AdminPartenairesRouteImport.update({
  id: '/partenaires',
  path: '/partenaires',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjetsRoute = AdminProjetsRouteImport.update({
  id: '/projets',
  path: '/projets',
  getParentRoute: () => AdminRoute,
} as any)
const LocaleNewsIndexRoute = LocaleNewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleNewsSlugRoute = LocaleNewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleProjectsIndexRoute = LocaleProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleProjectsSlugRoute = LocaleProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => LocaleRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/actions': typeof LocaleActionsRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/gallery': typeof LocaleGalleryRoute
  '/$locale/partners': typeof LocalePartnersRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/actualites': typeof AdminActualitesRoute
  '/admin/chiffres': typeof AdminChiffresRoute
  '/admin/galerie': typeof AdminGalerieRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/partenaires': typeof AdminPartenairesRoute
  '/admin/projets': typeof AdminProjetsRoute
  '/$locale/': typeof LocaleIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/$locale/news/$slug': typeof LocaleNewsSlugRoute
  '/$locale/projects/$slug': typeof LocaleProjectsSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/$locale/news/': typeof LocaleNewsIndexRoute
  '/$locale/projects/': typeof LocaleProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/actions': typeof LocaleActionsRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/gallery': typeof LocaleGalleryRoute
  '/$locale/partners': typeof LocalePartnersRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/actualites': typeof AdminActualitesRoute
  '/admin/chiffres': typeof AdminChiffresRoute
  '/admin/galerie': typeof AdminGalerieRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/partenaires': typeof AdminPartenairesRoute
  '/admin/projets': typeof AdminProjetsRoute
  '/$locale': typeof LocaleIndexRoute
  '/admin': typeof AdminIndexRoute
  '/$locale/news/$slug': typeof LocaleNewsSlugRoute
  '/$locale/projects/$slug': typeof LocaleProjectsSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/$locale/news': typeof LocaleNewsIndexRoute
  '/$locale/projects': typeof LocaleProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/actions': typeof LocaleActionsRoute
  '/$locale/contact': typeof LocaleContactRoute
  '/$locale/gallery': typeof LocaleGalleryRoute
  '/$locale/partners': typeof LocalePartnersRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/actualites': typeof AdminActualitesRoute
  '/admin/chiffres': typeof AdminChiffresRoute
  '/admin/galerie': typeof AdminGalerieRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/partenaires': typeof AdminPartenairesRoute
  '/admin/projets': typeof AdminProjetsRoute
  '/$locale/': typeof LocaleIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/$locale/news/$slug': typeof LocaleNewsSlugRoute
  '/$locale/projects/$slug': typeof LocaleProjectsSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/$locale/news/': typeof LocaleNewsIndexRoute
  '/$locale/projects/': typeof LocaleProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/admin'
    | '/mcp'
    | '/sitemap.xml'
    | '/$locale/about'
    | '/$locale/actions'
    | '/$locale/contact'
    | '/$locale/gallery'
    | '/$locale/partners'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/actualites'
    | '/admin/chiffres'
    | '/admin/galerie'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/partenaires'
    | '/admin/projets'
    | '/$locale/'
    | '/admin/'
    | '/$locale/news/$slug'
    | '/$locale/projects/$slug'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/$locale/news/'
    | '/$locale/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mcp'
    | '/sitemap.xml'
    | '/$locale/about'
    | '/$locale/actions'
    | '/$locale/contact'
    | '/$locale/gallery'
    | '/$locale/partners'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/actualites'
    | '/admin/chiffres'
    | '/admin/galerie'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/partenaires'
    | '/admin/projets'
    | '/$locale'
    | '/admin'
    | '/$locale/news/$slug'
    | '/$locale/projects/$slug'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/$locale/news'
    | '/$locale/projects'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/admin'
    | '/mcp'
    | '/sitemap.xml'
    | '/$locale/about'
    | '/$locale/actions'
    | '/$locale/contact'
    | '/$locale/gallery'
    | '/$locale/partners'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/actualites'
    | '/admin/chiffres'
    | '/admin/galerie'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/partenaires'
    | '/admin/projets'
    | '/$locale/'
    | '/admin/'
    | '/$locale/news/$slug'
    | '/$locale/projects/$slug'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/$locale/news/'
    | '/$locale/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  McpRoute: typeof McpRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/about': {
      id: '/$locale/about'
      path: '/about'
      fullPath: '/$locale/about'
      preLoaderRoute: typeof LocaleAboutRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/actions': {
      id: '/$locale/actions'
      path: '/actions'
      fullPath: '/$locale/actions'
      preLoaderRoute: typeof LocaleActionsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/contact': {
      id: '/$locale/contact'
      path: '/contact'
      fullPath: '/$locale/contact'
      preLoaderRoute: typeof LocaleContactRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/gallery': {
      id: '/$locale/gallery'
      path: '/gallery'
      fullPath: '/$locale/gallery'
      preLoaderRoute: typeof LocaleGalleryRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/partners': {
      id: '/$locale/partners'
      path: '/partners'
      fullPath: '/$locale/partners'
      preLoaderRoute: typeof LocalePartnersRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/actualites': {
      id: '/admin/actualites'
      path: '/actualites'
      fullPath: '/admin/actualites'
      preLoaderRoute: typeof AdminActualitesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chiffres': {
      id: '/admin/chiffres'
      path: '/chiffres'
      fullPath: '/admin/chiffres'
      preLoaderRoute: typeof AdminChiffresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/galerie': {
      id: '/admin/galerie'
      path: '/galerie'
      fullPath: '/admin/galerie'
      preLoaderRoute: typeof AdminGalerieRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/partenaires': {
      id: '/admin/partenaires'
      path: '/partenaires'
      fullPath: '/admin/partenaires'
      preLoaderRoute: typeof AdminPartenairesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projets': {
      id: '/admin/projets'
      path: '/projets'
      fullPath: '/admin/projets'
      preLoaderRoute: typeof AdminProjetsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$locale/news/': {
      id: '/$locale/news/'
      path: '/news'
      fullPath: '/$locale/news/'
      preLoaderRoute: typeof LocaleNewsIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/news/$slug': {
      id: '/$locale/news/$slug'
      path: '/news/$slug'
      fullPath: '/$locale/news/$slug'
      preLoaderRoute: typeof LocaleNewsSlugRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/projects/': {
      id: '/$locale/projects/'
      path: '/projects'
      fullPath: '/$locale/projects/'
      preLoaderRoute: typeof LocaleProjectsIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/projects/$slug': {
      id: '/$locale/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/$locale/projects/$slug'
      preLoaderRoute: typeof LocaleProjectsSlugRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LocaleRouteChildren {
  LocaleAboutRoute: typeof LocaleAboutRoute
  LocaleActionsRoute: typeof LocaleActionsRoute
  LocaleContactRoute: typeof LocaleContactRoute
  LocaleGalleryRoute: typeof LocaleGalleryRoute
  LocalePartnersRoute: typeof LocalePartnersRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleNewsSlugRoute: typeof LocaleNewsSlugRoute
  LocaleProjectsSlugRoute: typeof LocaleProjectsSlugRoute
  LocaleNewsIndexRoute: typeof LocaleNewsIndexRoute
  LocaleProjectsIndexRoute: typeof LocaleProjectsIndexRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleAboutRoute: LocaleAboutRoute,
  LocaleActionsRoute: LocaleActionsRoute,
  LocaleContactRoute: LocaleContactRoute,
  LocaleGalleryRoute: LocaleGalleryRoute,
  LocalePartnersRoute: LocalePartnersRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleNewsSlugRoute: LocaleNewsSlugRoute,
  LocaleProjectsSlugRoute: LocaleProjectsSlugRoute,
  LocaleNewsIndexRoute: LocaleNewsIndexRoute,
  LocaleProjectsIndexRoute: LocaleProjectsIndexRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

interface AdminRouteChildren {
  AdminActualitesRoute: typeof AdminActualitesRoute
  AdminChiffresRoute: typeof AdminChiffresRoute
  AdminGalerieRoute: typeof AdminGalerieRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminPartenairesRoute: typeof AdminPartenairesRoute
  AdminProjetsRoute: typeof AdminProjetsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActualitesRoute: AdminActualitesRoute,
  AdminChiffresRoute: AdminChiffresRoute,
  AdminGalerieRoute: AdminGalerieRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminPartenairesRoute: AdminPartenairesRoute,
  AdminProjetsRoute: AdminProjetsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  McpRoute: McpRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
